estados = {
  1: {"uf": "AC", "estado": "Acre"},
  2: {"uf": "AL", "estado": "Alagoas"},
  3: {"uf": "AP", "estado": "Amapá"},
  4: {"uf": "AM", "estado": "Amazonas"},
  5: {"uf": "BA", "estado": "Bahia"},
  6: {"uf": "CE", "estado": "Ceará"},
  7: {"uf": "DF", "estado": "Distrito Federal"},
  8: {"uf": "ES", "estado": "Espírito Santo"},
  9: {"uf": "GO", "estado": "Goiás"},
  10: {"uf": "MA", "estado": "Maranhão"},
  11: {"uf": "MT", "estado": "Mato Grosso"},
  12: {"uf": "MS", "estado": "Mato Grosso do Sul"},
  13: {"uf": "MG", "estado": "Minas Gerais"},
  14: {"uf": "PA", "estado": "Pará"},
  15: {"uf": "PB", "estado": "Paraíba"},
  16: {"uf": "PR", "estado": "Paraná"},
  17: {"uf": "PE", "estado": "Pernambuco"},
  18: {"uf": "PI", "estado": "Piauí"},
  19: {"uf": "RJ", "estado": "Rio de Janeiro"},
  20: {"uf": "RN", "estado": "Rio Grande do Norte"},
  21: {"uf": "RS", "estado": "Rio Grande do Sul"},
  22: {"uf": "RO", "estado": "Rondônia"},
  23: {"uf": "RR", "estado": "Roraima"},
  24: {"uf": "SC", "estado": "Santa Catarina"},
  25: {"uf": "SP", "estado": "São Paulo"},
  26: {"uf": "SE", "estado": "Sergipe"},
  27: {"uf": "TO", "estado": "Tocantins"}
}